#pragma once


#ifndef GRAPHIC_CORE_OPENGL
#define GRAPHIC_CORE_OPENGL 1
#endif // !GRAPHIC_CORE_OPENGL

#ifndef GRAPHIC_CORE_DIRECTX11
#define GRAPHIC_CORE_DIRECTX11 0
#endif // !GRAPHIC_CORE_DIRECTX11

#ifndef GRAPHIC_CORE_VULKAN
#define GRAPHIC_CORE_VULKAN 0
#endif // !GRAPHIC_CORE_VULKAN

#ifndef GRAPHIC_CORE_DIRECTX12
#define GRAPHIC_CORE_DIRECTX12 0
#endif // !GRAPHIC_CORE_DIRECTX12

#define GRAPHIC_LEFT_HAND_SYSTEM 0
#define GRAPHIC_RIGHT_HAND_SYSTEM 1 

#define GRAPHIC_DEPTH_ZERO_TO_ONE				0x00000001
#define GRAPHIC_DEPTH_NEGATIVE_ONE_TO_ONE		0x00000002

#ifdef GRAPHIC_FORCE_DEPTH_ZERO_TO_ONE
#	define GRAPHIC_DEPTH_CLIP_SPACE GRAPHIC_DEPTH_ZERO_TO_ONE
#else
#	define GRAPHIC_DEPTH_CLIP_SPACE GRAPHIC_DEPTH_NEGATIVE_ONE_TO_ONE
#endif

#define GRAPHIC_CORE_MAX_TEXTURE 4096u

#define GRAPHIC_CORE_MAX_FRAMEBUFFER 1024u

#define GRAPHIC_CORE_MAX_SAMPLER 32u

#define GRAPHIC_CORE_MAX_UNIFORM 1024u

#define GRAPHIC_CORE_MAX_SHADER 256u 

 
